### ISSUE TITLE
1. Array & Hashing#1

### ISSUE THREAD

**Issue by lukasjhan** [tree-s-computer/alg-practice#2]
@yunseorim1116 

1~2주차는 Array & Hashing입니다.

### 1주차

https://leetcode.com/problems/contains-duplicate/description/

https://leetcode.com/problems/two-sum/description/

**Comment by yunseorim1116** [comment]
1주차 완료했습니다~
시간나실때 리뷰 부탁드립니다 !

**Comment by lukasjhan** [comment]
> 1주차 완료했습니다~
> 시간나실때 리뷰 부탁드립니다 !

엄청 빠르시네요 ㅎㅎㅎ

사실 2개가 1주차랍니다.

**Comment by yunseorim1116** [comment]
후딱 풀었습니다..!!

**Comment by lukasjhan** [comment]
아 깜빡하고 말씀못드린게 있는데요. 중요한 점이 있습니다. @yunseorim1116 

### 푸는게 아니라 푸는 방식을 공부한다는 마음가짐으로 해야합니다.

### 푸는데 2시간 이상 걸리면 말씀해주세요. 푸는 방법에 대해서 같이 확인해봅시다.
