### ISSUE TITLE
1. Array & Hashing#2

### ISSUE THREAD

**Issue by lukasjhan** [tree-s-computer/alg-practice#4]
2주차는 Array & Hashing 조금 더 어려운문제를 풀어봅시다. 

https://leetcode.com/problems/top-k-frequent-elements/description/

https://leetcode.com/problems/longest-consecutive-sequence/

**Comment by lukasjhan** [comment]
각각 1~2시간정도 풀어봅시다 :)
그 후에 같이 봐요.

**Comment by lukasjhan** [comment]
고생하셨습니다 :) 

학습목표.
1. 생각하는 순서: 무작정 구현 -> 어떤걸 더 잘할 수 있을까.
2. Hash하는 이유는 탐색시간을 줄이기 위해서이다.
    ex) 1이 몇번 나오는지를 구해야하는데 매번 구하지말고 어디 구해서 적어놓을 수 있을까?

**Comment by lukasjhan** [comment]
![image](https://github.com/tree-s-computer/alg-practice/assets/86042901/bae76528-562d-45c5-91f7-d3e9ac5379c9)

**Comment by yunseorim1116** [comment]
[Quick Sort]
![image](https://github.com/tree-s-computer/alg-practice/assets/94429667/97d16865-8c0f-4381-a5aa-1999484204ae)

**Comment by yunseorim1116** [comment]
![image](https://github.com/tree-s-computer/alg-practice/assets/94429667/cbed9cd0-1a3f-40f1-b8d9-e6e33b8afced)

**[어떻게 풀까?]**
![image](https://github.com/tree-s-computer/alg-practice/assets/94429667/1caa80da-fc61-4aaa-9826-7154ff55835c)


**힌트** : 인덱스를 활용하자!

**중요한 것 정리** (학습목표)
1. 무작정 구현후-> 1번 방식을 최적화 하는게 접근법
2. Hash하는 이유는 탐색시간을 줄이기 위해서이다.  
ex:) 1이 몇번 나오는지를 구해야 하는데 매번 구하지 말고 구해서 어디게 적어놓을 수 있을까 ?
