### ISSUE TITLE
2. Stack#3

### ISSUE THREAD

**Issue by lukasjhan** [tree-s-computer/alg-practice#6]
이번주와 다음주는 stack에 대해서 공부해봅시다.

https://leetcode.com/problems/min-stack/description/

https://leetcode.com/problems/evaluate-reverse-polish-notation/description/

**Comment by yunseorim1116** [comment]
[evaluate-reverse-polish-notation/description/](https://leetcode.com/problems/evaluate-reverse-polish-notation/description/)
이 문제가 왜 저한테 어려울까? 라고 곰곰히 생각해봤는데, 역폴란드 표기법이 저한테는 좀 낯설어서 문제 자체를 이해하는 것이 어려웠던 것 같아요.
문제 풀이를 몇 개 보고 이해했습니다.

**Comment by lukasjhan** [comment]
그쵸 2 + 3을 2 3 +로 표기하는 방법이에요.
표기법을 변경하면 괄호가 필요없다는 장점이 있습니다.
